/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as MunnarHomestaysRouteImport } from './routes/munnar-homestays'
import { Route as WayanadResortsRouteImport } from './routes/wayanad-resorts'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as PackagesSlugRouteImport } from './routes/packages/$slug'
import { Route as PropertySlugRouteImport } from './routes/property/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MunnarHomestaysRoute = MunnarHomestaysRouteImport.update({
  id: '/munnar-homestays',
  path: '/munnar-homestays',
  getParentRoute: () => rootRouteImport,
} as any)
const WayanadResortsRoute = WayanadResortsRouteImport.update({
  id: '/wayanad-resorts',
  path: '/wayanad-resorts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/listings': typeof ListingsRoute
  '/munnar-homestays': typeof MunnarHomestaysRoute
  '/wayanad-resorts': typeof WayanadResortsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/listings': typeof ListingsRoute
  '/munnar-homestays': typeof MunnarHomestaysRoute
  '/wayanad-resorts': typeof WayanadResortsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/blog': typeof BlogIndexRoute
  '/journal': typeof JournalIndexRoute
  '/packages': typeof PackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/listings': typeof ListingsRoute
  '/munnar-homestays': typeof MunnarHomestaysRoute
  '/wayanad-resorts': typeof WayanadResortsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/packages/': typeof PackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/experiences'
    | '/listings'
    | '/munnar-homestays'
    | '/wayanad-resorts'
    | '/blog/$slug'
    | '/journal/$slug'
    | '/packages/$slug'
    | '/property/$slug'
    | '/blog/'
    | '/journal/'
    | '/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/experiences'
    | '/listings'
    | '/munnar-homestays'
    | '/wayanad-resorts'
    | '/blog/$slug'
    | '/journal/$slug'
    | '/packages/$slug'
    | '/property/$slug'
    | '/blog'
    | '/journal'
    | '/packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/experiences'
    | '/listings'
    | '/munnar-homestays'
    | '/wayanad-resorts'
    | '/blog/$slug'
    | '/journal/$slug'
    | '/packages/$slug'
    | '/property/$slug'
    | '/blog/'
    | '/journal/'
    | '/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRoute
  ListingsRoute: typeof ListingsRoute
  MunnarHomestaysRoute: typeof MunnarHomestaysRoute
  WayanadResortsRoute: typeof WayanadResortsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  PropertySlugRoute: typeof PropertySlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munnar-homestays': {
      id: '/munnar-homestays'
      path: '/munnar-homestays'
      fullPath: '/munnar-homestays'
      preLoaderRoute: typeof MunnarHomestaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wayanad-resorts': {
      id: '/wayanad-resorts'
      path: '/wayanad-resorts'
      fullPath: '/wayanad-resorts'
      preLoaderRoute: typeof WayanadResortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRoute,
  ListingsRoute: ListingsRoute,
  MunnarHomestaysRoute: MunnarHomestaysRoute,
  WayanadResortsRoute: WayanadResortsRoute,
  BlogSlugRoute: BlogSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  PropertySlugRoute: PropertySlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
